name: Discord Notification

on:
  push:
    branches:
      - main
  release:

jobs:
    discord_notification:
        runs-on: ubuntu-latest
        steps:
        - name: Send HTTP Request
          id: http_request
          run: |
            curl "https://api.sentinelx.org/api/v1/github/embed/?description=You%20can%20find%20the%20update%20[HERE](https://github.com/Sentinel-X-Bot/Teamspeak/releases)"
