name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notify
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'Sentinel X - Teamspeak releases'
          DISCORD_AVATAR: 'https://sentinelx.org/assets/img/branding/sentinel.png'
          DISCORD_EMBEDS: >
            [
              {
                "author": {"name": "Teamspeak Integration Update", "icon_url": "https://sentinelx.org/assets/img/branding/sentinel.png", "url": "SET-THIS-TO-RELEASE-URL"},
                "title": "Teamspeak Integration Update",
                "description": "CHANGE-LOG-HERE",
                "color": 2829617
              }
            ]
        uses: Ilshidur/action-discord@master
        with:
          args: 'Test'
