name: Discord Notification

on:
  release:
    types: [created]

jobs:
    discord_notification:
        runs-on: ubuntu-latest
        steps:
        - name: Send HTTP Request
          id: http_request
          run: |
            curl "https://api.sentinelx.org/api/v1/github/embed/?key=${{ secrets.SECURE_KEY }}"
