name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Print push description
        run: |
          echo "Push description: ${{ github.event.head_commit.message }}"
#