name: Discord Notification

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project ${{ github.event.repository.full_name }} has been deployed.'
