name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Print push description
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          DESCRIPTION=$(echo "$COMMIT_MESSAGE" | sed '1d')
          echo "Push description: $DESCRIPTION"
