name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notify
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'Sentinel X - Teamspeak releases'
          DISCORD_AVATAR: 'https://sentinelx.org/assets/img/branding/sentinel.png'
          DISCORD_EMBEDS: '[{"author": {"name": "Teamspeak Intergration Update","icon_url": "https://sentinelx.org/assets/img/branding/sentinel.png","url": "SET-THIS-TO-RELEASE-URL"},"description": "CHANGE-LOG-HERE","color": "#00b0f4",}]'
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project ${{ github.repository }} has been deployed.'
